### ISSUE TITLE
Adding Automatic Area path Set

### ISSUE THREAD

**Issue by CarloAlbertoS** [LorenzoScebba/azure-boards-pbi-autorule#13]
Is it possible to add the possibility to automatically set a different area path based on specific (custom) work item types?

the need is to manage two (or ideally n) different areas in the same DevOps project and link a specific subset of work items to one of them, being able automatically override the default Area.

E.g.:
Project1 -> default Area
Project2 
a new "task" is created -> no action needed, using Project1 as area
a new "custom task" is created -> webhook triggered and set project2

**Comment by LorenzoScebba** [comment]
So from my understanding,

Let's say I have a PBI with its area path set to "MyAreaPath/Area1", once I add a custom work item of type "Custom Task" (linked to the PBI)  its area path would be automatically set to "MyAreaPath/Area1", this feature would enable users to say that ALL the Custom Tasks created should be set under the area path "MyAreaPath/Area2" right?

Also would be a filter needed? 
E.G: Only the Custom Tasks created under  "MyAreaPath/Area1" should be moved to  "MyAreaPath/Area2", if a Custom Task is created under  "MyAreaPath/Area3" it should NOT be moved to  "MyAreaPath/Area2".

The configuration could look something like this

```json
{
   ...previousConfigs
   "AreaRules":[
      {
         "Type":"Custom Task",
         "Rules":[
            {
               "IfAreaPath":"MyAreaPath/Area1",
               "SetAreaPathTo":"MyAreaPath/Area2"
            }
         ]
      }
   ]
}
```

**Comment by CarloAlbertoS** [comment]
The scenario is this one:
I defined different areas in my project and assigned them to the team:
![image](https://user-images.githubusercontent.com/44276647/133077796-1bca8c50-8335-45f8-9800-6d7193ec0682.png)

When I create a new PBI the area path is set to "HC_2\Area1" which is default, but I need that for a certain set of PBI types this value is overridden with a user defined area (e.g. "HC_2\Area2").

The filter is not necessary because it is not important which is the area assigned at the creation (it can be the default or even another one set manually), but it is important that it is changed with the needed one.

The configuration could be even simpler, ideally it would be great to have the "type" field definable as an array of strings:

```
{
   ...previousConfigs
   "AreaRules":[
      {
         "Type":"Custom Task",
         "Rules":[
            {
               "SetAreaPathTo":"HC_2\Area2"
            }
         ]
      }
   ]
}

```
